---
- name: deploy master samba DC
  hosts: master
  become: false
  roles:
  - role: samba

- name: deploy samba DC replicas
  hosts: replicas
  become: false
  roles:
  - role: samba

- name: deploy samba clients
  hosts: clients
  become: false
  roles:
  - role: samba

