---
- name: Check bind work in chroot
  command: control bind-chroot
  register: bind_chrooted
  check_mode: no
  changed_when: False

- name: Disable bind work in chroot
  command: control bind-chroot disabled
  when: " 'disabled' not in bind_chrooted.stdout "

- name: Disable KRB5RCACHETYPE for bind
  lineinfile:
    path: /etc/sysconfig/bind
    regexp: '^[ #/;]*KRB5RCACHETYPE=.*'
    line: 'KRB5RCACHETYPE="none"'
    state: present

- name: Add BIND9_DLZ plugin for bind
  lineinfile:
    path: /etc/bind/named.conf
    regexp: '^[ #/;]*include.*".*/var/lib/samba/bind-dns/named.conf.*".*;'
    line: 'include "/var/lib/samba/bind-dns/named.conf";'
    state: present

- name: generate options.conf for bind
  template:
    src: options.conf.j2
    dest: /etc/bind/options.conf

- name: enable bind service
  service:
    name: bind
    enabled: true
  register: cmd_result
  failed_when: "cmd_result is failed and ('find' not in cmd_result.msg and 'found' not in cmd_result.msg)"
