---
- name: Disable bind work in chroot
  shell: control bind-chroot disabled

- name: Disable KRB5RCACHETYPE for bind
  shell: grep -q KRB5RCACHETYPE /etc/sysconfig/bind || echo 'KRB5RCACHETYPE="none"' >> /etc/sysconfig/bind

- name: Check if 'bind-dns' option is present in /etc/bind/named.conf
  lineinfile:
    path: /etc/bind/named.conf
    line: "bind-dns"
    state: present
  check_mode: yes
  register: bind_dns_option

- name: Include named.conf from Samba config dir
  lineinfile:
    path: /etc/bind/named.conf
    state: present
    line: include "/var/lib/samba/bind-dns/named.conf";
  when: not bind_dns_option.found

- name: generate options.conf for bind
  template:
    src: options.conf.j2
    dest: /etc/bind/options.conf
