---
- name: create /etc/krb5.conf
  template:
    src: krb5.conf.j2
    dest: /etc/krb5.conf
    owner: root
    group: root
    mode: 0644
  notify: restart samba

- name: create dir for kdc.conf
  file:
    path: "/usr/local/samba/private"
    state: directory

- name: create kdc.conf
  template:
    src: kdc.conf.j2
    dest: /usr/local/samba/private/kdc.conf
    owner: root
    group: root
    mode: 0644
  notify: restart samba

- name: create openldap config directory
  file:
    path: "/etc/openldap"
    state: directory

- name: disable reverse dns for ldap requests
  template:
    src: ldap.conf.j2
    dest: /etc/openldap/ldap.conf
  notify: restart samba
