---
- name: check required variables
  fail: msg="{{ item }} is not defined"
  when: item not in vars
  with_items: "{{ samba_dc_master_required_vars }}"

- name: generate samba controller config files
  include_tasks: dc_conf.yml

- name: generate smb.conf
  include_tasks: smb.conf.yml

- name: prepare bind service
  include_tasks: bind.yml
  when: samba_dns_backend != "SAMBA_INTERNAL"

- name: install samba master packages
  apt_rpm:
    pkg: "{{ samba_dc_master_packages }}"
    state: present
  when: samba_dc_master_packages | length > 0
  notify: restart samba

- name: remove conflict samba server packages
  apt_rpm:
    pkg:
      - nss-ldapd
      - nscd
    state: absent
  notify: restart samba

- name: check if already provisioned
  stat:
    path: "/var/lib/samba/.ansible_provisioned"
  register: samba_provisioned

- name: provition domain
  block:
    - name: stop BIND9 daemon
      service:
        name: bind
        state: stopped
      register: cmd_result
      failed_when: "cmd_result is failed and ('find' not in cmd_result.msg and 'found' not in cmd_result.msg)"

    - name: stop Samba DC
      service:
        name: samba
        state: stopped

    - name: start provisioning domain
      include_tasks: master_provision.yml
  rescue:
    - name: provision failed; remove intermidiate results
      file:
        path: "/var/lib/samba"
        state: absent
    - fail: msg="domain provision failed"
  when: samba_provisioned.stat.exists == False or samba_deploy_soft == False

- name: create provision state file
  copy:
    content: ""
    dest: /var/lib/samba/.ansible_provisioned
    force: no

- name: create sites for master dc
  include_tasks: sites.yml

- name: disable bind service
  service:
    name: bind
    enabled: false
    state: stopped
  when: samba_dns_backend == "SAMBA_INTERNAL"
  register: cmd_result
  failed_when: "cmd_result is failed and ('find' not in cmd_result.msg and 'found' not in cmd_result.msg)"

- name: enable samba service
  service:
    name: samba
    enabled: true

- name: start bind service
  service:
    name: bind
    state: started
  when: samba_dns_backend != "SAMBA_INTERNAL"
  register: cmd_result
  failed_when: "cmd_result is failed and ('find' not in cmd_result.msg and 'found' not in cmd_result.msg)"

- name: start samba service
  service:
    name: samba
    state: started

- name: register node in localhost hostvars
  set_fact:
    samba_masters: "{{ hostvars['localhost']['samba_masters'] | default([]) }} + [ '{{ inventory_hostname_short }}' ]"
  delegate_to: localhost
  delegate_facts: true
