---
- name: check required variables
  fail: msg="{{ item }} is not defined"
  when: item not in vars
  with_items: "{{ samba_dc_master_required_vars }}"

- name: create sites
  shell: |
    set -euo pipefail
    samba-tool sites create {{ item.key }}
  loop: "{{ samba_sites | dict2items }}"
  when: "{{ item.key != samba_site }}"

- name: create site subnets
  shell: |
    set -euo pipefail
    samba-tool sites subnet create {{ item.value.subnet }} {{ item.key }}
  loop: "{{ samba_sites | dict2items }}"
