---
- name: check required variables
  fail: msg="{{ item }} is not defined"
  when: item not in vars
  with_items: "{{ samba_dc_master_required_vars }}"

- name: create sites
  shell: |
    set -euo pipefail
    samba-tool sites create {{ item.key }}
  register: site_create
  failed_when: site_create.rc != 0 and "SiteAlreadyExistsException" not in site_create.stderr
  changed_when: site_create.rc == 0
  loop: "{{ samba_sites | dict2items }}"
  when: item.key != samba_site

- name: create site subnets
  shell: |
    set -euo pipefail
    samba-tool sites subnet create {{ item.value.subnet }} {{ item.key }}
  register: site_subnet
  failed_when: site_subnet.rc != 0 and "already exists" not in site_subnet.stderr
  changed_when: site_subnet.rc == 0
  loop: "{{ samba_sites | dict2items }}"
