---
- name: restart samba
  service:
    name: samba
    enabled: true
    state: restarted

- name: restart networkmanager
  service:
    name: NetworkManager
    state: restarted

- name: restart network
  service:
    name: network
    state: restarted

- name: restart bind
  service:
    name: bind
    state: restarted

- name: networkmanager reconnect
  shell: nmcli connection up eth0
